/**
 * A region group: a named set of IATA region codes.
 *
 * Region groups are DB-sourced (the region_groups ClickHouse table is the single source of truth,
 * seeded by ingest/migrations/004 and regenerated by scripts/generate-region-groups.ts). The app
 * reads them via getRegionGroups() (cached) for display, and resolves them in SQL for filtering —
 * there is no hardcoded membership in TS to keep in sync.
 */
export interface RegionGroup {
  /** Stable, IATA-disjoint group code (slug), e.g. "pacific-northwest". */
  code: string;
  /** Display name, e.g. "Pacific Northwest". */
  name: string;
  /** Member IATA region codes (uppercase). */
  members: string[];
}
